app = "mailmarketing-app"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  AUTH_TOKEN = "changeme"
  DB_PATH = "/data/db.sqlite"
  UPLOAD_DIR = "/data/uploads"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
